name: 🚀 Deploy website on push

on:
  workflow_dispatch:
  push:
    branches:
      - 3395

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.rexord.com
          username: ea-deploy@rexord.com
          password: P!s%gbivXwGI