# Deploy to WP.org
name: Deploy to WordPress.org

on:
  push:
    branches: [ deploy ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm install --silent && npm run build